services:
  node:
    build: ./server

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node